name: Deploy Static Site to GitHub Pages

on:
  push:
    branches:
      - main  # Ganti ke "master" jika Anda pakai branch master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload Static Files
        uses: actions/upload-pages-artifact@v3
        with:
          path: Frontend  # ⚠️ Tanpa './' dan tanpa '/' di akhir — ini penting!

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
